system:
  type: train
  device: cuda

wandb:
  use: False
  project: goat

logger:
  save_dir: log
  save_freq: 1

molecule:
  name: alanine
  start_state: c5
  end_state: c7ax

path:
  num_steps: 10
  bias_scale: 0.01
  scale: 1

dynamics:
  temperature: 300.0
  timestep: 1.0

training:
  num_samples: 4
  trains_per_rollout: 10
  batch_size: 16
  feat_aug: dist
  start_temperature: 600
  end_temperature: 300
  max_grad_norm: 1
  num_rollouts: 1000
  log_z_lr: 1e-2
  policy_lr: 1e-4
  prioritized_exp: 1
  buffer_size: 20
